### PR TITLE
Stage

### PR DESCRIPTION
**Pull request by amandauzowulu**
Hello Team,

Please review and share your thoughts on these updates. 

Thanks
Amanda

### CODE REVIEW

**Review by luizy28 — CHANGES_REQUESTED** [review]
I think that Jesus should be written with the the first letter in Caps and also you don't need the hallelujah in line 1

**Comment by luizy28** [comment]
It says that there is no conflict with the base branch. Why the merge?

**Comment by amandauzowulu** [comment]
There is conflicts . Not sure what are looking at. 


Sent from Yahoo Mail for iPhone


On Wednesday, May 31, 2023, 7:22 PM, luizy28 ***@***.***> wrote:




It says that there is no conflict with the base branch. Why the merge?

**Comment by amandauzowulu** [comment]
merging branch to continue working. review from members will be looked at later.

**Review by luizy28 — COMMENTED** [review]
.

**Pull request merged**
